### ISSUE TITLE
Error "./cloudflare: line 14: [: missing `]'"

### ISSUE THREAD

**Issue by masterlog80** [namnamir/configurations-and-security-hardening#6]
Hello,
I am running the script on `DDNS.md` in order to update my DNS records for Cloudflare. Despite the script seems running properly, every time I do run it (by `bash cloudflare.sh` or `./cloudflare.sh`) I get the following output:
```
# ./cloudflare 
./cloudflare: line 14: [: missing `]'
grep: ]: No such file or directory
 [+] Your public IPv4 address: 11....
```
I have taken a look at public docs like [this](https://superuser.com/questions/927154/), [this](https://stackoverflow.com/questions/35281797) and other ones, but I can't get rid of that unexpected warning. I am wondering if due to that the first `if` conditions may get ignored: it's not a big deal, but I am wondering if you may have a workaround.

Regards,

**Comment by thomastthai** [comment]
You may want to post your script so people can inspect it. Sometimes that error could be due to a needed space.

**Comment by namnamir** [comment]
It seems that your bash doesn't support `grep`, which is needed. I have added a control to check it and yield an error message.
