### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by tristesky** [namnamir/configurations-and-security-hardening#7]
I have set up the A record, but it prompts an error

![eeor](https://user-images.githubusercontent.com/52591934/202880078-572fdd1e-656e-4a02-b659-a239ae262bed.jpg)

**Comment by scyllaL** [comment]
I guess you have to install the package 'bind-tools' or something similar, as the script wants to use dig, which seems not to be installed on your machine.

**Comment by namnamir** [comment]
As @scyllaL mentioned, it seems that it is related not being able to use `dig`.
